# -*- coding: utf-8 -*-
"""LaptopBatteryPercentage_mejorado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BnBMNfG_XDYuRFe4ITFSzUz4A9FVT6Cs
"""

# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# load dataset
df = pd.read_csv('battery_health_dataset.csv')

# get dataset info
df.info()

# Identificar si hay datos nulos
print('DATOS NULOS:')
print(df.isnull().sum())

# Identificar si hay filas duplicadas
print('\n\nDATOS DUPLICADOS:')
print(df.duplicated().unique()[0])

# Visualizar datos atipicos (outliers)

# Eliminar variable categorica
boxplot_df = df.drop(columns=['Gaming User'])
boxplot_columns = boxplot_df.columns

# Definir numero de filas y columnas de los subplotse y tamano de la figura
fig, axes = plt.subplots(
    nrows=3,
    ncols=3,
    figsize=(15, 10)
)

# Graficar boxplot de cada variable numerica
# zip() junta cada subplot con su columna correspondiente
for ax, column in zip(axes.flat, boxplot_columns):

    sns.boxplot(
        x=boxplot_df[column],
        ax=ax
    )

    ax.set_title(column)
    ax.set_xlabel('')


plt.suptitle(
    'Box Plots of Features',
    fontsize=20
)

plt.tight_layout()
plt.show()

# Visualizar correlacion entre variables

# Obtener matriz de correlacion
correlation_matrix = df.corr()

# Graficar mapa de calor
plt.figure(figsize=(12, 9))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm',
    vmin=-1,
    vmax=1,
    center=0,
    fmt='.2f',
    linewidths=0.5
)

plt.title('Correlation of All Variables', fontsize=16)

plt.tight_layout()
plt.show()

# Eliminar columnas Full Charge Capacity y Design Capacity
df.drop(columns=['Full Charge Capacity', 'Design Capacity'], inplace=True)

# Aplicar shuffle al dataset para asegurar que los datos esten al azar al momento de separarlos en train, test y validation
df_shuffled = df.sample(frac=1, random_state=42).reset_index(drop=True)

# Dividir Dataset en df_x y df_y
df_x = df_shuffled.drop(columns=['Battery Health'])
df_y = df_shuffled['Battery Health']

# MEJORA - Terminos cuadraticos
#
# La grafica de residuales del modelo lineal muestra curvatura: las
# baterias de 60-70 % de salud quedan siempre por encima de la diagonal,
# o sea el modelo les predice mas salud de la que tienen. Battery Age y
# Cycle Count son las dos variables mas predictoras (correlacion de
# -0.90 y -0.92 con el target), asi que se agregan sus cuadrados para
# que el modelo pueda curvar la relacion en lugar de solo trazar una
# recta.
#
# Los cuadrados se calculan sobre los valores ORIGINALES, antes de
# estandarizar. Al reves, (x - mu)^2 no es proporcional a x^2 y el
# termino cuadratico pierde su interpretacion.
#
# El modelo sigue siendo lineal EN LOS PARAMETROS, asi que el mismo
# gradiente descendiente funciona sin cambios: lo unico que cambia es
# la matriz de entrada.

df_x['Battery Age^2'] = df_x['Battery Age'] ** 2
df_x['Cycle Count^2'] = df_x['Cycle Count'] ** 2

# Dividir df_x y df_y en train y test

# Train (80%)
df_x_train = df_x[:960]
df_y_train = df_y[:960]

# Validation (10%)
df_x_val = df_x[960:1080]
df_y_val = df_y[960:1080]

# Test (10%)
df_x_test = df_x[1080:1200]
df_y_test = df_y[1080:1200]

def fit_standardize(X):
    means = X.mean()
    stds = X.std()

    return means, stds


def transform_standardize(X, means, stds):

    X_scaled = X.copy()

    for column in X.columns:
        X_scaled[column] = (
            X[column] - means[column]
        ) / stds[column]

    return X_scaled

continuous_variables = [
    'Battery Age',
    'Daily Usage Hours',
    'Cycle Count',
    'CPU Usage',
    'GPU Usage',
    'Power Consumption',
    'Average Temperature',
    # MEJORA - los terminos cuadraticos tambien se estandarizan.
    # Sin esto quedarian en sus unidades originales (Cycle Count^2
    # llega a 2,250,000) y dominarian por completo el gradiente.
    'Battery Age^2',
    'Cycle Count^2',
]

# Estandarizar datos

df_x_train_scaled = df_x_train.copy()
df_x_val_scaled = df_x_val.copy()
df_x_test_scaled = df_x_test.copy()

means, stds = fit_standardize(df_x_train[continuous_variables])

df_x_train_scaled = df_x_train.copy()
df_x_val_scaled = df_x_val.copy()
df_x_test_scaled = df_x_test.copy()

df_x_train_scaled[continuous_variables] = transform_standardize(
    df_x_train[continuous_variables], means, stds
)

df_x_val_scaled[continuous_variables] = transform_standardize(
    df_x_val[continuous_variables], means, stds
)

df_x_test_scaled[continuous_variables] = transform_standardize(
    df_x_test[continuous_variables], means, stds
)


X_train = df_x_train_scaled.to_numpy(dtype=float)
X_val = df_x_val_scaled.to_numpy(dtype=float)
X_test = df_x_test_scaled.to_numpy(dtype=float)

Y_train = df_y_train.to_numpy(dtype=float)
Y_val = df_y_val.to_numpy(dtype=float)
Y_test = df_y_test.to_numpy(dtype=float)

print('X_train', X_train.shape, '| X_val',
      X_val.shape, '| X_test', X_test.shape)

"""
Funcion de hipotesis
Calcula la prediccion
por cada parametro.
input:
    params: parametros
    x_row: fila del arreglo de X
output:
    y_pred: y (prediccion)
"""


def hyp(params, x_row):

    y_pred = params[0]

    for j in range(1, len(params)):
        y_pred += params[j] * x_row[j - 1]

    return y_pred

"""
Funcion de Prediccion
Aplica la hipotesis a cada fila del arreglo X.
"""
def predict_all(params, X):
    predicciones = []

    for i in range(len(X)):
        predicciones.append(hyp(params, X[i]))

    return np.array(predicciones)

"""
Funcion de costo - Mean Squared Error (MSE)
"""
def mse(params, X, Y_real):

    acum = 0.0
    n = len(X)

    for i in range(n):
        y_pred = hyp(params, X[i])
        acum += (y_pred - Y_real[i]) ** 2

    return acum / n

"""
Funcion de optimizacion - Gradiente Descendiente
"""
def grad_desc(params, X, Y_real, alpha):
    params = np.array(params, dtype=float)
    n = len(X)

    gradients = np.zeros(len(params))

    errors = np.zeros(n)

    for i in range(n):
        errors[i] = hyp(params, X[i]) - Y_real[i]

    for j in range(len(params)):

        acum = 0.0
        for i in range(n):
            if j == 0:
                acum += errors[i] * 1
            else:
                acum += errors[i] * X[i][j - 1]

        gradients[j] = (1 / n) * acum

    new_params = params - alpha * gradients

    return new_params

def optimize(max_epochs, og_parameters, X, Y, alpha, X_val, Y_val):
    params = np.array(og_parameters, dtype=float)

    loss_array = []
    theta_array = []
    val_loss_array = []

    for epoch in range(max_epochs + 1):

        params = grad_desc(params, X, Y, alpha)
        theta_array.append(params.copy())

        loss = mse(params, X, Y)
        loss_array.append(loss)

        val_loss = mse(params, X_val, Y_val)
        val_loss_array.append(val_loss)

        if epoch % 100 == 0 or epoch == max_epochs:
            print(
                f"Epoch {epoch}: Loss = {loss:}    Val Loss = {val_loss:}")

    print("\nFin de la optimizacion")

    return params, loss_array, theta_array, val_loss_array

"""
    Función del coeficiente de determinacion
    R2 = 1 - SS_res / SS_tot
    Proporcion de la varianza de la target variable explicada por el modelo.
    """
def r2(y_true, y_pred):
    n = len(y_true)

    suma = 0
    for i in range(n):
        suma += y_true[i]
    media = suma / n

    ss_res = 0
    ss_tot = 0
    for i in range(n):
        ss_res += (y_true[i] - y_pred[i]) ** 2
        ss_tot += (y_true[i] - media) ** 2

    return 1.0 - ss_res / ss_tot

feature_names = list(df_x.columns)

params = np.zeros(len(feature_names) + 1)

ALPHA = 0.35
EPOCHS = 3000

final_params, loss_array, theta_array, val_loss_array = optimize(
    EPOCHS,
    params,
    X_train,
    Y_train,
    ALPHA,
    X_val,
    Y_val
)

print('\nPARAMETROS FINALES')
print(f'  {"Sesgo (theta_0)":<25} {final_params[0]:>10.4f}')
for j, nombre in enumerate(feature_names):
    print(f'  {nombre:<25} {final_params[j + 1]:>10.4f}')

plt.plot(loss_array)

plt.xlabel('Epoch')
plt.ylabel('Loss Train')
plt.title('Loss vs Epoch')

plt.show()

plt.plot(val_loss_array)

plt.xlabel('Epoch')
plt.ylabel('Loss Validation')
plt.title('Loss vs Epoch')

plt.show()

test_loss_array = []

for th in theta_array:
    test_loss_array.append(mse(th, X_test, Y_test))


plt.plot(test_loss_array)

plt.xlabel('Epoch')
plt.ylabel('Loss Test')
plt.title('Loss vs Epoch')

plt.show()

# Predicciones del modelo en los tres conjuntos
Y_pred_train = predict_all(final_params, X_train)
Y_pred_val = predict_all(final_params, X_val)
Y_pred_test = predict_all(final_params, X_test)

# Lista (nombre, y_real, y_predicho) que se reutiliza mas abajo
splits = [
    ('Train',      Y_train, Y_pred_train),
    ('Validation', Y_val,   Y_pred_val),
    ('Test',       Y_test,  Y_pred_test),
]

tabla_r2 = pd.DataFrame([
    {
        'Conjunto': nombre,
        'n': len(y_real),
        'R2': r2(y_real, y_pred),
    }
    for nombre, y_real, y_pred in splits
]).set_index('Conjunto')

print('=' * 50)
print('R2 POR CONJUNTO')
print('=' * 50)
print(tabla_r2.round(4).to_string())

# La brecha entre train y validation/test es lo que indica sobreajuste.
brecha = tabla_r2.loc['Train', 'R2'] - tabla_r2.loc['Test', 'R2']
print(f'\nBrecha R2 train - test: {brecha:+.4f}')

if brecha > 0.10:
    print('-> El modelo pierde bastante desempeno fuera de train (sobreajuste).')
else:
    print('-> El desempeno se sostiene fuera de train: no hay sobreajuste.')

COLORES = {
    'Train':      '#0072B2',
    'Validation': '#E69F00',
    'Test':       '#009E73',
}


curvas = [
    ('Train',      loss_array),
    ('Validation', val_loss_array),
    ('Test',       test_loss_array),
]

print('=' * 64)
print('PERDIDA DURANTE EL ENTRENAMIENTO')
print('=' * 64)
print(f"{'Conjunto':<12} {'inicial':>11} {'final':>10}")

for nombre, curva in curvas:
    arr = np.array(curva)
    print(f'{nombre:<12} {arr[0]:>11.4f} {arr[-1]:>10.4f}')

# Limites comunes para los tres paneles
todos = np.concatenate([np.concatenate([yr, yp]) for _, yr, yp in splits])
margen = (todos.max() - todos.min()) * 0.05
lo = todos.min() - margen
hi = todos.max() + margen

fig, axes = plt.subplots(1, 3, figsize=(16, 5.5), sharex=True, sharey=True)

for ax, (nombre, y_real, y_pred) in zip(axes, splits):

    ax.plot([lo, hi], [lo, hi],
            linestyle='--', linewidth=2, color='#999999', zorder=1)

    ax.scatter(y_real, y_pred,
               s=28, alpha=0.75, color=COLORES[nombre],
               edgecolor='white', linewidth=0.5, zorder=2)

    ax.text(0.04, 0.96,
            f'$R^2$ = {r2(y_real, y_pred):.4f}',
            transform=ax.transAxes, va='top', ha='left', fontsize=12,
            bbox=dict(boxstyle='round,pad=0.4', facecolor='white',
                      edgecolor='#dddddd', alpha=0.9))

    ax.set_xlim(lo, hi)
    ax.set_ylim(lo, hi)
    ax.set_aspect('equal')

    ax.set_title(f'{nombre}   (n = {len(y_real)})', fontsize=13)
    ax.set_xlabel('Actual Battery Health')
    ax.grid(True, alpha=0.25, linewidth=0.6)
    ax.set_axisbelow(True)

axes[0].set_ylabel('Predicted Battery Health')

fig.suptitle('Actual vs Predicted Battery Health', fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.94])
plt.show()