# -*- coding: utf-8 -*-
"""LaptopBatteryPercentage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qEoFLZikY6-UnMOId8lbbZRLAHW4jUhu
"""

# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# load dataset
df = pd.read_csv('battery_health_dataset.csv')

# get dataset info
df.info()

# Identificar si hay datos nulos
print('DATOS NULOS:')
print(df.isnull().sum())

# Identificar si hay filas duplicadas
print('\n\nDATOS DUPLICADOS:')
print(df.duplicated().unique()[0])

# Visualizar datos atipicos (outliers)

# Eliminar variable categorica
boxplot_df = df.drop(columns=['Gaming User'])
boxplot_columns = boxplot_df.columns

# Definir numero de filas y columnas de los subplotse y tamano de la figura
fig, axes = plt.subplots(
    nrows=3,
    ncols=3,
    figsize=(15, 10)
)

# Graficar boxplot de cada variable numerica
# zip() junta cada subplot con su columna correspondiente
for ax, column in zip(axes.flat, boxplot_columns):

    sns.boxplot(
        x=boxplot_df[column],
        ax=ax
    )

    ax.set_title(column)
    ax.set_xlabel('')


plt.suptitle(
    'Box Plots of Features',
    fontsize=20
)

plt.tight_layout()
plt.show()

# Visualizar correlacion entre variables

# Obtener matriz de correlacion
correlation_matrix = df.corr()

# Graficar mapa de calor
plt.figure(figsize=(12, 9))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm',
    vmin=-1,
    vmax=1,
    center=0,
    fmt='.2f',
    linewidths=0.5
)

plt.title('Correlation of All Variables', fontsize=16)

plt.tight_layout()
plt.show()

# Eliminar columnas Full Charge Capacity y Design Capacity
#df.drop(columns=['Full Charge Capacity', 'Design Capacity'], inplace=True)

# Aplicar shuffle al dataset para asegurar que los datos esten al azar al momento de separarlos en train, test y validation
df_shuffled = df.sample(frac=1, random_state=42).reset_index(drop=True)

# Dividir Dataset en df_x y df_y
df_x = df_shuffled.drop(columns=['Battery Health'])
df_y = df_shuffled['Battery Health']

# Dividir df_x y df_y en train y test

# Train (80%)
df_x_train = df_x[:960]
df_y_train = df_y[:960]

# Test (20%)
df_x_test = df_x[960:1200]
df_y_test = df_y[960:1200]

def fit_standardize(X):
    means = X.mean()
    stds = X.std()

    return means, stds


def transform_standardize(X, means, stds):

    X_scaled = X.copy()

    for column in X.columns:
        X_scaled[column] = (
            X[column] - means[column]
        ) / stds[column]

    return X_scaled

continuous_variables = [
    'Battery Age',
    'Daily Usage Hours',
    'Cycle Count',
    'CPU Usage',
    'GPU Usage',
    'Power Consumption',
    'Average Temperature',
]

means, stds = fit_standardize(df_x_train[continuous_variables])

df_x_train_scaled = df_x_train.copy()
df_x_test_scaled = df_x_test.copy()

df_x_train_scaled[continuous_variables] = transform_standardize(
    df_x_train[continuous_variables], means, stds
)

df_x_test_scaled[continuous_variables] = transform_standardize(
    df_x_test[continuous_variables], means, stds
)

"""
Funcion de hipotesis
Calcula la prediccion
por cada parametro.
input:
    params: parametros
    X: arreglo de x
output:
    y_pred: y (prediccion)
"""
def hyp(params, X):

    y_pred = params[0]

    for j in range(1, len(params)):
        y_pred += params[j] * X[j-1]

    return y_pred

"""
Funcion de costo - Mean Squared Error (MSE)
"""
def mse(params, X, Y_real):

    acum = 0
    n = len(X)

    for i in range(n):
        y_pred = hyp(params, X)
        acum = acum + ((y_pred - Y_real[i])**2)

    acum = acum/n
    return acum

"""
Funcion de optimizacion - Gradiente Descendiente
"""
def grad_desc(params, X, Y_real, alpha):

    new_params = np.array(params, dtype=float)

    X = X.to_numpy()
    Y_real = Y_real.to_numpy()

    for j in range(len(params)):

        acum = 0

        for i in range(len(X)):

            prediction = hyp(params, X[i])

            loss = prediction - Y_real[i]

            acum += loss * X[i][j]

        gradient = (1 / len(X)) * acum

        new_params[j] = params[j] - alpha * gradient

    return new_params

def optimize(max_epochs, og_parameters, X, Y, alpha):

    params = np.array(og_parameters, dtype=float)

    loss_array = []
    theta_array = []

    for epoch in range(max_epochs+1):

        params = grad_desc(params,X,Y,alpha)

        theta_array.append(params.copy())

        # Calcular loss
        predictions = np.array([
            hyp(params, row)
            for row in X.to_numpy()
        ])

        loss = np.mean((predictions - Y.to_numpy()) ** 2)

        loss_array.append(loss)

        if epoch % 100 == 0 or epoch == 1000:
            print(f"Epoch {epoch}: Loss = {loss}")

    print("Fin de la optimizacion")
    print(params)

    return params, loss_array, theta_array

final_params, loss_array, theta_array = optimize(
    1000,
    [0,0,0,0,0,0,0,0],
    df_x_train_scaled,
    df_y_train,
    0.0001
)

plt.plot(loss_array)

plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Loss vs Epoch')

plt.show()

X_train_np = df_x_train_scaled.to_numpy()

Y_pred = []

for row in X_train_np:
    prediction = hyp(final_params, row)
    Y_pred.append(prediction)

Y_pred = np.array(Y_pred)
Y_train = df_y_train.to_numpy()

results = pd.DataFrame({
    'Actual': Y_train,
    'Predicted': Y_pred
})

print(results)

plt.figure(figsize=(8, 6))

plt.scatter(Y_train, Y_pred)

plt.plot(
    [Y_train.min(), Y_train.max()],
    [Y_train.min(), Y_train.max()],
    linestyle='--'
)

plt.xlabel('Actual Battery Health')
plt.ylabel('Predicted Battery Health')
plt.title('Actual vs Predicted Battery Health')

plt.grid(True)
plt.show()

X_test_np = df_x_test_scaled.to_numpy()

Y_pred = []

for row in X_test_np:
    prediction = hyp(final_params, row)
    Y_pred.append(prediction)

Y_pred = np.array(Y_pred)
Y_test = df_y_test.to_numpy()

results = pd.DataFrame({
    'Actual': Y_test,
    'Predicted': Y_pred
})

print(results)

plt.figure(figsize=(8, 6))

plt.scatter(Y_test, Y_pred)

plt.plot(
    [Y_test.min(), Y_test.max()],
    [Y_test.min(), Y_test.max()],
    linestyle='--'
)

plt.xlabel('Actual Battery Health')
plt.ylabel('Predicted Battery Health')
plt.title('Actual vs Predicted Battery Health')

plt.grid(True)
plt.show()